ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_icp
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_icp/icp_hw/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_icp/icp_hw/ipe_hw
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_icp/fw_inc
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += ipe_dev.o ipe_core.o ipe_soc.o
