ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_cci
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu/
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core

obj-$(CONFIG_SPECTRA_CAMERA) += cam_eeprom_dev.o cam_eeprom_core.o cam_eeprom_soc.o
