ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cdm
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu/
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += hw_utils/ isp_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_isp_hw_mgr.o cam_ife_hw_mgr.o

