ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_res_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_cci
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu/

obj-$(CONFIG_CAMERA_FW_UPDATE) += fw_update.o PhoneUpdate.o
