ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sync

obj-$(CONFIG_SPECTRA_CAMERA) += cam_sync.o cam_sync_util.o
