ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr

obj-$(CONFIG_SPECTRA_CAMERA) += cam_smmu_api.o
