ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sync
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cdm
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_fd
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_fd/fd_hw_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += fd_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_fd_hw_mgr.o
