ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_hyp_intf
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
