ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_smmu/
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sync
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cdm/
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_vsync

obj-$(CONFIG_SPECTRA_CAMERA) += isp_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_isp_dev.o cam_isp_context.o
