ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas/include
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_floral/cam_cpas

obj-$(CONFIG_SPECTRA_CAMERA) += cam_cpastop_hw.o
